# Generated by Django 4.0.4 on 2022-04-24 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_status_alter_item_roll_number_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
        migrations.AddField(
            model_name='item',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stat',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='Roll_Number_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='Roll_Number_2',
            field=models.CharField(max_length=10),
        ),
    ]
