# Generated by Django 4.0.4 on 2022-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_date_time_item_in_date_time_remove_item_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_date_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='out_date_time',
            field=models.CharField(max_length=10),
        ),
    ]
