# Generated by Django 4.0.4 on 2022-04-26 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_item_in_date_time_alter_item_out_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='out_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
